In [1]:
import pandas as pd, numpy as np, csv
filename = 'soc-sign-bitcoinotc.csv'
file = open(filename, "r")
reader = csv.reader(file)

data = {}
for row in reader:
    if((row[0] in data) and (int(row[2])>=8)):
        data[row[0]].append(row[1])
    elif(int(row[2]) >= 8):
        data[row[0]] = [row[1]]

## Create connection matrix (Matrix A)

In [2]:
matrixA = np.zeros((6005,6005))
for i in data:
    size = len(list(map(int, data[i])))
    for j in data[i]:
        matrixA.itemset((int(j)-1, int(i)-1), 1.0/size)

## Create matrix B

In [3]:
matrixB = np.empty((6005,6005))
result = 0.15/6005
matrixB.fill(result)

## Create matrix V

In [4]:
matrixV = 1.0/6005 * np.ones((6005, 1))

## Calculate M

In [5]:
m = (0.85 * matrixA) + matrixB

## Calculate pageRank

In [6]:
count = 0
def pageRank(matrixV):
    global count
    if((sum(abs((m.dot(matrixV))-matrixV))) > 0.001):
        count +=1
        print(count)
        print(m.dot(matrixV))
        print(sum(abs((m.dot(matrixV))-matrixV)))
        return pageRank(m.dot(matrixV))
    else:
        count+=1
        print(count)
        print(m.dot(matrixV))
        print(sum(abs((m.dot(matrixV))-matrixV)))
        return m.dot(matrixV)

In [7]:
result = pageRank(matrixV)
print(result)
print(sorted(result, reverse=True))

1
[[3.11163977e-03]
 [1.91191684e-04]
 [4.07068184e-05]
 ...
 [2.49791840e-05]
 [2.49791840e-05]
 [2.49791840e-05]]
[0.82222989]
2
[[1.88120168e-03]
 [4.36051202e-04]
 [2.42152660e-05]
 ...
 [6.15827360e-06]
 [6.15827360e-06]
 [6.15827360e-06]]
[0.16293495]
3
[[2.00737869e-03]
 [3.02718968e-04]
 [4.38317188e-05]
 ...
 [2.64910530e-06]
 [2.64910530e-06]
 [2.64910530e-06]]
[0.0476409]
4
[[1.10910688e-03]
 [3.05990233e-04]
 [3.02541422e-05]
 ...
 [1.66401742e-06]
 [1.66401742e-06]
 [1.66401742e-06]]
[0.0218485]
5
[[1.02198096e-03]
 [1.93882544e-04]
 [3.01058539e-05]
 ...
 [1.20677637e-06]
 [1.20677637e-06]
 [1.20677637e-06]]
[0.01363054]
6
[[6.12879966e-04]
 [1.69820770e-04]
 [1.92296260e-05]
 ...
 [9.18496830e-07]
 [9.18496830e-07]
 [9.18496830e-07]]
[0.00944731]
7
[[5.46555146e-04]
 [1.11151215e-04]
 [1.67519715e-05]
 ...
 [7.13343289e-07]
 [7.13343289e-07]
 [7.13343289e-07]]
[0.00690752]
8
[[3.43947806e-04]
 [9.35018731e-05]
 [1.10587855e-05]
 ...
 [5.61170733e-07]
 [5.61170733e-07]
 [