In [27]:
import pandas as pd, numpy as np, csv
filename = 'soc-sign-bitcoinotc.csv'
file = open(filename, "r")
reader = csv.reader(file)

data = {}
for row in reader:
    if((int(row[0]) in data) and (int(row[2])>=8)):
        data[int(row[0])].append(int(row[1]))
    elif(int(row[2]) >= 8):
        data[int(row[0])] = [int(row[1])]

## Create connection matrix (Matrix A)

In [28]:
matrixA = np.zeros((6005,6005))
for i in data:
    size = len(list(map(int, data[i])))
    for j in data[i]:
        matrixA.itemset((int(j)-1, int(i)-1), 1.0/size)
print(matrixA)

[[ 0.          0.11111111  0.         ...,  0.          0.          0.        ]
 [ 0.09090909  0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.11111111  0.         ...,  0.          0.          0.        ]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]]


## Create matrix B

In [29]:
matrixB = np.empty((6005,6005))
result = 0.15/6005
matrixB.fill(result)
print(matrixB)

[[  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 ..., 
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]]


## Create matrix V

In [30]:
matrixV = 1.0/6005 * np.ones((6005, 1))
print(matrixV)

[[ 0.00016653]
 [ 0.00016653]
 [ 0.00016653]
 ..., 
 [ 0.00016653]
 [ 0.00016653]
 [ 0.00016653]]


## Calculate M

In [32]:
m = (0.85 * matrixA) + matrixB
print(m)

[[  2.49791840e-05   9.44694236e-02   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  7.72977065e-02   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   9.44694236e-02   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 ..., 
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]
 [  2.49791840e-05   2.49791840e-05   2.49791840e-05 ...,   2.49791840e-05
    2.49791840e-05   2.49791840e-05]]


## Calculate pageRank

In [33]:
count = 0
def pageRank(matrixV):
    global count
    if((sum(abs((m.dot(matrixV))-matrixV))) > 0.001):
        count +=1
        print(count)
        print(m.dot(matrixV))
        print(sum(abs((m.dot(matrixV))-matrixV)))
        return pageRank(m.dot(matrixV))
    else:
        count+=1
        print(count)
        print(m.dot(matrixV))
        print(sum(abs((m.dot(matrixV))-matrixV)))
        return m.dot(matrixV)

In [48]:
result = pageRank(matrixV)
print(result)
#print indice de maior pagerank
print(list(result).index(sorted(result, reverse=True)[0]))

196
[[  3.11163977e-03]
 [  1.91191684e-04]
 [  4.07068184e-05]
 ..., 
 [  2.49791840e-05]
 [  2.49791840e-05]
 [  2.49791840e-05]]
[ 0.82222989]
197
[[  1.88120168e-03]
 [  4.36051202e-04]
 [  2.42152660e-05]
 ..., 
 [  6.15827360e-06]
 [  6.15827360e-06]
 [  6.15827360e-06]]
[ 0.16293495]
198
[[  2.00737869e-03]
 [  3.02718968e-04]
 [  4.38317188e-05]
 ..., 
 [  2.64910530e-06]
 [  2.64910530e-06]
 [  2.64910530e-06]]
[ 0.0476409]
199
[[  1.10910688e-03]
 [  3.05990233e-04]
 [  3.02541422e-05]
 ..., 
 [  1.66401742e-06]
 [  1.66401742e-06]
 [  1.66401742e-06]]
[ 0.0218485]
200
[[  1.02198096e-03]
 [  1.93882544e-04]
 [  3.01058539e-05]
 ..., 
 [  1.20677637e-06]
 [  1.20677637e-06]
 [  1.20677637e-06]]
[ 0.01363054]
201
[[  6.12879966e-04]
 [  1.69820770e-04]
 [  1.92296260e-05]
 ..., 
 [  9.18496830e-07]
 [  9.18496830e-07]
 [  9.18496830e-07]]
[ 0.00944731]
202
[[  5.46555146e-04]
 [  1.11151215e-04]
 [  1.67519715e-05]
 ..., 
 [  7.13343289e-07]
 [  7.13343289e-07]
 [  7.13343289e